deployment:
  tasks:
    - export DEPLOYPATH=/home/gstsaudicpanel/public_html/react/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R assets index.html favicon.png placeholder.svg robots.txt .htaccess $DEPLOYPATH
